In [1]:
import pandas as pd
import os
import datetime
import pickle
import numpy as np

In [35]:
train_data = pd.read_csv('data/insiderDat_June_clean.csv')

historicDat = {'June': pd.read_pickle('data/historicDat_June.pkl'),
              'July': pd.read_pickle('data/historicDat_July.pkl'),
              'August': pd.read_pickle('data/historicDat_August.pkl'),
              'September': pd.read_pickle('data/historicDat_Sept.pkl'),
              'October': pd.read_pickle('data/historicDat_Oct.pkl'),
              'November': pd.read_pickle('data/historicDat_Nov.pkl')}

In [45]:
# getting all ticker data together per ticker for each month
## for each ticker, loop through each month and paste together dataset
months = ['June','July', 'August', 'September', 'October', 'November']
allTickers = historicDat['July'].keys()
tickerDat = {}
for t in allTickers:
    tickDat = []
    for m in months:
        tickDat.append(historicDat[m][t])
    tickerDat[t] = pd.concat(tickDat)

In [ ]:
# getting max/min ticker % change over one, three or five months
## get value on June 1 for all tickers
## compute max change for each month on the 30th or 31st (cumulative), put into df unique by ticker
refDat = pd.DataFrame(np.nan, index = allTickers, columns = ['ref', '10%', '50%', '100%'])
delta = datetime.datetime.strptime('2021-07-31', '%Y-%m-%d') - datetime.datetime.strptime('2021-06-01', '%Y-%m-%d')

June_July_days = []
for i in range(delta.days + 1):
    June_July_days.append(datetime.datetime.strptime('2021-06-01', '%Y-%m-%d') + datetime.timedelta(days=i))

for t in allTickers:
    try: 
        refval = tickerDat[t][tickerDat[t].index == '2021-06-01']['Open'][0]
        refDat['ref'][refDat.index == t] = refval
        maxJuly = max(tickerDat[t][tickerDat[t].index.isin(June_July_days)]['Open'])
        perChange = (maxJuly-refval)/refval
        
        if perChange < 0.10:
            refDat['10%'][refDat.index == t] = 0
            refDat['50%'][refDat.index == t] = 0
            refDat['100%'][refDat.index == t] = 0
        elif (perChange >= 0.10) & (perChange < 0.50):
            refDat['10%'][refDat.index == t] = 0
            refDat['50%'][refDat.index == t] = 0
            refDat['100%'][refDat.index == t] = 1
        elif (perChange >= 0.50) & (perChange < 1):
            refDat['10%'][refDat.index == t] = 0
            refDat['50%'][refDat.index == t] = 1
            refDat['100%'][refDat.index == t] = 0
        elif perChange >= 1:
            refDat['10%'][refDat.index == t] = 0
            refDat['50%'][refDat.index == t] = 0
            refDat['100%'][refDat.index == t] = 1
    except:
        print('This ticker didn t work: {}'.format(t))

This ticker didn t work: SPKAU
This ticker didn t work: SVMK
This ticker didn t work: ISNS
This ticker didn t work: GTXMQ
This ticker didn t work: TCF

In [141]:
refDat

             ref  10%  50%  100%
IBP   119.379997  NaN  NaN   NaN
DXC    37.860001  NaN  NaN   NaN
REVG   19.000000  0.0  0.0   1.0
AMST    2.440000  0.0  1.0   0.0
TLYS   13.890000  0.0  0.0   1.0
...          ...  ...  ...   ...
NWPP    2.075000  NaN  NaN   NaN
LIVE   55.180000  0.0  0.0   1.0
FICO  510.790009  NaN  NaN   NaN
PLRX   30.160000  NaN  NaN   NaN
CFX    44.689999  NaN  NaN   NaN

[913 rows x 4 columns]